# Generated by Django 3.1.7 on 2021-02-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_name_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='plant_family',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
