# Generated by Django 3.1.7 on 2021-02-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_plant_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='plant_family',
        ),
    ]
